import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { AiFillTwitterCircle, AiFillGithub } from "react-icons/ai";
import { BsFacebook, BsFillDatabaseFill } from "react-icons/bs";
import { SiAffinitydesigner } from "react-icons/si";
import { DiHtml5 } from "react-icons/di";
import { CgWebsite } from "react-icons/cg";
import { ImStatsBars } from "react-icons/im";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Haider Irfan</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* HERO SECTION */}

      <section className={styles.hero}>
        <h1>
          {" "}
          <span>Hello I'm</span> <br /> Haider Irfan{" "}
        </h1>
      </section>

      {/* ABOUT SECTION */}

      <section className={styles.about}>
        <div className={styles.image}>
          <img src="/menpic.webp" alt="" />
        </div>
        <div className={styles.text}>
          <h2 className={styles.backtitle}>About</h2>
          <h3 className={styles.fronttitle}>Hi! I am Haider Irfan</h3>
          <p>
            I would like to introduce myself as a highly skilled web developer.
            Throughout my career, I have acquired extensive expertise and
            hands-on experience in the field of web development. I possess a
            deep understanding of various programming languages, frameworks, and
            technologies that are essential for creating dynamic and interactive
            websites.
          </p>
          <div className={styles.socials}>
            <AiFillTwitterCircle className={styles.twitter} />
            <BsFacebook className={styles.facebook} />
            <AiFillGithub className={styles.github} />
          </div>
          <div className={styles.contact}>
            <h2 className={styles.tt}>Contact me here !</h2>
            <h3>
              <span>Email:</span>&nbsp;&nbsp;haiderrirfann@gmail.com
            </h3>
            <h3>
              <span>Phone:</span>&nbsp;&nbsp;+92-318-4139306
            </h3>
          </div>
        </div>
      </section>

      {/* SERVICES SECTION */}

      <section className={styles.services}>
        <h3>What I Do</h3>
        <h2>My Services</h2>
        <div className={styles.subsec}>
          <div className={styles.service}>
            <SiAffinitydesigner className={styles.design} />
            <h2>
              UI/UX <br /> Design
            </h2>
          </div>
          <div className={styles.service}>
            <DiHtml5 className={styles.design} />
            <h2>Front End development</h2>
          </div>
          <div className={styles.service}>
            <BsFillDatabaseFill className={styles.design} />
            <h2>Back end development</h2>
          </div>
          <div className={styles.service}>
            <CgWebsite className={styles.design} />
            <h2>Full stack development</h2>
          </div>
          <div className={styles.service}>
            <ImStatsBars className={styles.design} />
            <h2>Web App Maintenance</h2>
          </div>
        </div>
      </section>

      {/* CONTACT SECTION */}

      <section className={styles.contactsec}>
        <h1>Are You Minding any project?</h1>
        <Link href={"mailto:haiderrirfann@gmail.com"}>
          <button className={styles.contactbtn}>Contact</button>
        </Link>
      </section>
    </>
  );
}
